---

- name: Create VLAN's on Arista
  hosts: arista

  tasks:
    - name: configure Eth6
      eos_interface: name=Ethernet6 description="*** IN USE ***"
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: configure Eth6 to trunk mode with vlan 144,244,344 as allowed
      eos_switchport: name=Ethernet6 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=144,244,344
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

