---

- name: Create VLAN's on Arista
  hosts: arista

  tasks:
    - name: configure Eth6
      eos_interface: name=Ethernet6 description="*** IN USE ***"
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: configure Eth6 access vlan 244
      eos_switchport: name=Ethernet6 mode=access access_vlan=244
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

