---

- name: Create VLAN's on Arista
  hosts: arista

  tasks:
    - name: Clear Eth6 descrition
      eos_interface: name=Ethernet6 description=""
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: Clear trunk Eth6 configuration
      eos_switchport: name=Ethernet6 mode=access access_vlan=1 trunk_native_vlan=1 trunk_allowed_vlans=1-4096
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: Delete VLANs
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}} state=absent
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https
      with_items:
        - {name: Black, vlanid: 144}
        - {name: White, vlanid: 244}
        - {name: Yellow, vlanid: 344}

