---

- name: CISCO file transfer test
  hosts: cisco
  gather_facts: False

  tasks:
  - name: File transfer
    cisco_file_transfer:
      source_file="cisco_logging_in.txt"
      dest_file="cisco_logging.txt"
      overwrite=true
      enable_scp=true
      host={{ host }}
      port={{ port }}
      username={{ username }}
      password={{ password }}
